export default {
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
  RECEIVE_SIGN_IN: 'RECEIVE_SIGN_IN',
  FAILED_SIGN_IN: 'FAILED_SIGN_IN',
  CHANGE_COMPONENT_TO_RENDER: 'CHANGE_COMPONENT_TO_RENDER',
  /**
   * User Details actions
   */
  REQUEST_USER_DETAILS: 'REQUEST_USER_DETAILS',
  RECEIVE_USER_DETAILS: 'RECEIVE_USER_DETAILS',
  FAILED_FETCH_USER_DETAILS: 'FAILED_FETCH_USER_DETAILS',
  /**
   * Official details
   */
  REQUEST_OFFICIAL_DETAILS: 'REQUEST_OFFICIAL_DETAILS',
  RECEIVE_OFFICIAL_DETAILS: 'RECEIVE_OFFICIAL_DETAILS',
  FAILED_FETCH_OFFICIAL_DETAILS: 'FAILED_FETCH_OFFICIAL_DETAILS',
  /**
   * Update Skill Ste
   */
  REQUEST_UPDATE_SKILL: 'REQUEST_UPDATE_SKILL',
  RECEIVE_UPDATE_SKILL: 'RECEIVE_UPDATE_SKILL',
  FAILED_TO_UPDATE_SKILL: 'FAILED_TO_UPDATE_SKILL',
  /**
   * Fetch Team Details
   */
  REQUEST_TEAM_DETAILS: 'REQUEST_TEAM_DETAILS',
  RECEIVE_TEAM_DETAILS: 'RECEIVE_TEAM_DETAILS',
  FAILED_TO_FETCH_TEAM_DETAILS: 'FAILED_TO_FETCH_TEAM_DETAILS',

  /**
   * Fetch descriptions Info
   */
  REQUEST_DESCRIPTION_DETAILS: 'REQUEST_DESCRIPTION_DETAILS',
  RECEIVE_DESCRIPTION_DETAILS: 'RECEIVE_DESCRIPTION_DETAILS',
  FETCH_FAILED_DESCRIPTION_DETAILS: 'FETCH_FAILED_DESCRIPTION_DETAILS',

  /**
   * Sign up
   */
  REQUEST_SIGN_UP: 'REQUEST_SIGN_UP',
  RECEIVE_SIGN_UP: 'RECEIVE_SIGN_UP',
  FAILED_TO_SIGN_UP: 'FAILED_TO_SIGN_UP',
  USER_ALREADY_REGISTERED: 'USER_ALREADY_REGISTERED',

  /**
   * Verify OTP
   */

  REQUEST_VERIFY_OTP: 'REQUEST_VERIFY_OTP',
  RECEIVED_VERIFY_OTP: 'RECEIVED_VERIFY_OTP',
  FAILED_TO_VERIFY_OTP: 'FAILED_TO_VERIFY_OTP',
};
