export default {
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
  RECEIVE_SIGN_IN: 'RECEIVE_SIGN_IN',
  FAILED_SIGN_IN: 'FAILED_SIGN_IN',
  CHANGE_COMPONENT_TO_RENDER: 'CHANGE_COMPONENT_TO_RENDER',
  /**
   * User Details actions
   */
  REQUEST_USER_DETAILS: 'REQUEST_USER_DETAILS',
  RECEIVE_USER_DETAILS: 'RECEIVE_USER_DETAILS',
  FAILED_FETCH_USER_DETAILS: 'FAILED_FETCH_USER_DETAILS',
  /**
   * Official details
   */
  REQUEST_OFFICIAL_DETAILS: 'REQUEST_OFFICIAL_DETAILS',
  RECEIVE_OFFICIAL_DETAILS: 'RECEIVE_OFFICIAL_DETAILS',
  FAILED_FETCH_OFFICIAL_DETAILS: 'FAILED_FETCH_OFFICIAL_DETAILS',
  /**
   * Update Skill Ste
   */
  REQUEST_UPDATE_SKILL: 'REQUEST_UPDATE_SKILL',
  RECEIVE_UPDATE_SKILL: 'RECEIVE_UPDATE_SKILL',
  FAILED_TO_UPDATE_SKILL: 'FAILED_TO_UPDATE_SKILL',
};
